Updated description for Fluentd k8s DaemonSet
logzio/logz-docs pull request #1136
Opened 2021-06-20 18:55 UTC by shishkinnico

# What changed

Specified which conf file is applicable to which DaemonSet.

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-06-23 12:53 UTC, mirii1994 requested changes

2021-06-23 12:53 UTC, mirii1994 commented on _source/_includes/log-shipping/multiline-fluentd-plugin.md
> +* `kubernetes.conf` for RBAC DaemonSet
```suggestion
* `kubernetes.conf` for RBAC/non-RBAC DaemonSet
```
This file also applies for non-RBAC daemonset :)

2021-06-24 19:31 UTC, YajB requested changes

2021-06-24 19:35 UTC, YajB approved these changes

2021-06-24 19:36 UTC, YajB approved these changes

2021-06-24 19:40 UTC, merged