Crowdstrike integration
logzio/logz-docs pull request #1138
Opened 2021-06-21 14:42 UTC by shishkinnico

# What changed

New document on Crowdstrike - SIEM integration

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-06-21 15:58 UTC, shishkinnico reviewed
Typo corrected

2021-06-21 16:03 UTC, shishkinnico reviewed
Style correction

2021-06-22 08:41 UTC, mirii1994 requested changes
Amazing job! please see my notes :)

2021-06-22 08:41 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/crowdstrike.md
> +3. Enter the Client Secret value into the **client_secret** value field.
```suggestion
2. Enter the Client ID value into the `client_id` value field.
3. Enter the Client Secret value into the `client_secret` value field.
```

Maybe we should do it like this?

2021-06-22 08:41 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/crowdstrike.md
> +4. Make sure that the base URL in `api_url` and `request_token_url` corresponds to the base URL for your account.
```suggestion
4. Make sure that the **base URL** in `api_url` and `request_token_url` corresponds to the base URL for your account.
```

2021-06-22 08:41 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/crowdstrike.md
> +   # Concating the event as one log
```suggestion
   # Concatenating the event as one log
```
My bad, typo :)

2021-06-22 10:17 UTC, shishkinnico commented
@mirii1994 Thank you for your comments, makes total sense, I've updated it.

2021-06-24 19:45 UTC, YajB approved these changes

2021-06-24 19:47 UTC, merged