Added a SYD document on fluentd on docker
logzio/logz-docs pull request #1158
Opened 2021-06-29 17:14 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-06-29 19:10 UTC, yotamloe requested changes
Amazing work Nico 🚀

2021-06-29 19:10 UTC, yotamloe commented on _source/logzio_collections/_log-sources/fluentd-docker.md
> +shipping-tags:
Can you add a reference to our os project, like in this doc:
![chrome-capture (5)](https://user-images.githubusercontent.com/48534558/123853378-1046eb80-d926-11eb-8627-e8c46185693d.jpg)
[The doc on github](https://github.com/logzio/logz-docs/blob/master/_source/logzio_collections/_metrics-sources/aws-cloudfront.md)

[Github repo](https://github.com/logzio/fluentd-docker-logs)

2021-06-29 19:10 UTC, yotamloe commented on _source/logzio_collections/_log-sources/fluentd-docker.md
> +If you still don’t see your data, see [log shipping troubleshooting](https://docs.logz.io/user-guide/log-shipping/log-shipping-troubleshooting.html).
I believe it's useful the add the full configurable parameters [list](https://github.com/logzio/fluentd-docker-logs/blob/main/README.md#parameters)

2021-06-30 12:38 UTC, nico-shishkin commented
Hi @yotamloe , thanks for the feedback! I've amended the document - could you please check? Thanks!

2021-06-30 14:47 UTC, yotamloe approved these changes
Amazing work

2021-07-06 15:58 UTC, ralongit approved these changes

2021-07-07 15:55 UTC, Doron-Bargo approved these changes
Great work

2021-07-08 10:22 UTC, merged