INT-365: Added a new document on Heroku telegraf
logzio/logz-docs pull request #1201
Opened 2021-07-12 17:14 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-07-13 06:41 UTC, Doron-Bargo requested changes
Please add a comment at the beginning steps that all commands should run from the heroku directory or something similar

2021-07-14 07:48 UTC, YajB approved these changes

2021-07-14 07:50 UTC, YajB reviewed
Change requested by @Doron-Bargo was implemented

2021-07-14 07:51 UTC, YajB commented
Changes requested by Doron were implemented. 
Merging the new integration

2021-07-14 07:51 UTC, merged