Added new Dotnet removed existing Dotnet
logzio/logz-docs pull request #1232
Opened 2021-07-22 14:40 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-07-22 16:16 UTC, Doron-Bargo requested changes

2021-07-22 16:16 UTC, Doron-Bargo commented on _source/logzio_collections/_tracing-sources/dotnet-otel-auto.md
> +```shell
This step is not working for me
Im getting an error on it and from the commands docs the syntax should be
dotnet add <PROJECT> package [options] <PACKAGE_NAME>
Or you need to run this command from the app directory?

2021-07-26 12:25 UTC, Doron-Bargo approved these changes

2021-07-26 14:44 UTC, YajB approved these changes
Removes 2 C# .NET open tracing topics and replaces them with .NET topic

2021-07-26 14:55 UTC, merged