Added a document on NSG log shipping
logzio/logz-docs pull request #1234
Opened 2021-07-25 17:03 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-07-26 13:02 UTC, Doron-Bargo requested changes
Hi, please see my comments

2021-07-26 13:02 UTC, Doron-Bargo commented on _source/logzio_collections/_log-sources/azure-nsg.md
> +
Please add a step to keep the storage name for the blob trigger step

2021-07-26 13:02 UTC, Doron-Bargo commented on _source/logzio_collections/_log-sources/azure-nsg.md
> +Connect your Azure Blob Storage account to Logz.io as described in the instructions [here](https://docs.logz.io/shipping/log-sources/azure-blob.html#existing-blob-config).
please split https://docs.logz.io/shipping/log-sources/azure-blob.html#existing-blob-config to something generic that we can add here

2021-08-01 13:50 UTC, YajB commented on _source/logzio_collections/_log-sources/azure-nsg.md
> +1. For your VM, navigate to **Networking > NSG > NSG flow**.
> We already have numbers on the title so maybe use letters here?

I disagree.  It is cognitively easier to process numbered steps in a procedure. 
Those titles are for procedures.

2021-08-02 17:11 UTC, YajB approved these changes
Resolved the issue of using numbers for substeps in higher level sections that are also sections

2021-08-02 17:14 UTC, merged