Added a document on dotnet custom metrics
logzio/logz-docs pull request #1270
Opened 2021-08-08 22:24 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-08-09 08:14 UTC, ShiranAvidov requested changes
Amazing work. It looks really good. I commented about couple of things that I believe should be changed, please take a look at them :)

2021-08-09 08:14 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +{% include log-shipping/listener-var.html %}
Please add to the listener examples the 'https://' or 'http://' and the port. If they use 'https://' the port is ':8053' and if they use 'http://' the port is ':8052'

2021-08-09 08:14 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +Some of the metrics have custom labels as described below.
You can write here that the clients should replace [[your_metric_name]] with their metric name.

2021-08-09 08:14 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +
You can remove the new line here :)

2021-08-09 08:14 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +                    options.FlushInterval = TimeSpan.FromSeconds(15);
Please change [[logzio_endpoint]] and [[metrics_token]] to be like the variables in the explanation (<<LISTENER-HOST>>)

2021-08-09 11:15 UTC, ShiranAvidov requested changes
4 last changes and you are done :)

2021-08-09 11:15 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +```
Please delete the Thread.Sleep lines (they are not relevant), and make the lines to start from same position as var counter line (you can even put a new line after first line and then the 2 metrics.Measure lines one after another)

2021-08-09 11:15 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +```
Same thing here :)

2021-08-09 11:15 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +```
last line need to be in same position as first line

2021-08-09 11:15 UTC, ShiranAvidov commented on _source/logzio_collections/_prometheus-sources/dotnet-custom.md
> +```
Same here :)

2021-08-09 11:46 UTC, ShiranAvidov approved these changes

2021-08-11 07:17 UTC, YajB approved these changes
Corrected typos, sentence structure.
Recommendation: Use snippets for blocks of text that appear in multiple locations in documents.

2021-08-11 07:17 UTC, merged