Added a doc on azure trigger
logzio/logz-docs pull request #1405
Opened 2021-09-26 11:10 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-09-27 11:54 UTC, Doron-Bargo approved these changes
lgtm
lets wait @ShiranAvidov to approve it as well

2021-09-29 08:20 UTC, ShiranAvidov requested changes
Great work :)

2021-09-29 08:20 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +The following services are created when you deploy this integration:
Please change this line to:
The following resources that are needed for this integration
or something like that :)

2021-09-29 08:20 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +
This is the full auto deployment section. The user will not see Storage Account Resource Name parameter (this is only for function auto deployment - this deployment will create the storage account in the same resource group so we do not need the user to fill this parameter :) )

2021-09-29 08:20 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +
Please add Storage Account Resource Name parameter :)

2021-09-29 08:20 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +
This integration does the exact opposite :)
Please change this info to:
Logs that were in the container before the deployment will be shipped to Logz.io. If these logs have already been shipped to Logz.io, we recommend that you empty the container before the deployment.

You can also put the information at the top of the page after the other info.

2021-09-29 10:26 UTC, ShiranAvidov requested changes

2021-09-29 10:26 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +The following services are needed for this integration:
instead of services please write resources.

2021-09-29 10:26 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +Logs that were in the container before the deployment will be shipped to Logz.io. If these logs have already been shipped to Logz.io, we recommend that you empty the container before the deployment.
you can remove this 2 lines.

2021-09-29 10:26 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +* The file name does not have to be with these extensions.
the last line should be an info

2021-09-29 10:28 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/azure-blob-trigger.md
> +Logs that were in the container before the deployment will be shipped to Logz.io. If these logs have already been shipped to Logz.io, we recommend that you empty the container before the deployment.
the last lines

2021-09-29 10:35 UTC, ShiranAvidov approved these changes

2021-09-29 11:35 UTC, merged