Added a page on azure vm extension
logzio/logz-docs pull request #1470
Opened 2021-10-26 11:39 UTC by nico-shishkin

# What changed

https://deploy-preview-1470--logz-docs.netlify.app/shipping/log-sources/azure-vm-extension.html
----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2021-11-10 09:34 UTC, Doron-Bargo commented
I dont like when we link to other companies pages
We should have the same documentation as Azure has on our extension

2021-11-29 19:44 UTC, Doron-Bargo requested changes
The flow looks ok
Please see my comments
Also - @mirii1994 can you give your opinion ?

2021-11-29 19:44 UTC, Doron-Bargo commented on _source/logzio_collections/_log-sources/azure-vm-extension.md
> +
need to add a note that we support only linux

2021-11-29 19:44 UTC, Doron-Bargo commented on _source/logzio_collections/_log-sources/azure-vm-extension.md
> +Log in to Logz.io using either the SSO in your Azure account or a link to the Logz.io platform.
Can you add pictures?

2021-11-30 07:34 UTC, mirii1994 approved these changes
lgtm, like doron said- we need to add a note that we support linux, and some screen shots for the steps

2021-12-15 13:25 UTC, merged