Added manual cloudformation deployment
logzio/logz-docs pull request #1635
Opened 2022-01-23 17:19 UTC by nico-shishkin

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2022-01-24 13:47 UTC, mirii1994 requested changes
Regarding all files -
1. Do you think maybe we should add either in the overview or in the tab itself, that the manual deployment uses Cloudwatch Public Registry?
2. I think it's worth mentioning that our Public Registry extensions are currently available only on the aws region us-east-1?
3. For the "Before you begin, you'll need" for the manual deployment - I don't think that they need an S3 bucket as a prerequisite.

2022-01-24 13:47 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +##### Activate the Logz.io Kinesis extension
```suggestion
##### Activate the Logz.io AWS Security Hub extension
```

2022-01-24 13:47 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| logzioLogLevel | Required log level.  |
I think it's worth mentioning the possible log levels that this integration allows, they are mentioned in the "automated deployment" tab

2022-01-24 13:47 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| logzioListener | {% include log-shipping/listener-var.html %} |
In this integration, they'll need to insert not only listener, but an http/https prefix, and the compatible port. For example - https://listener.logz.io:8071.
You can see in the automated deployment tab how we described it there

2022-01-24 13:47 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| logzioOperationsToken | Your Logz.io account token. {% include log-shipping/log-shipping-token.html %} |
There's no `<<LOG-SHIPPING-TOKEN>` in the code sample

2022-01-30 12:51 UTC, mirii1994 requested changes

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +                "logzioListener": "logzioListener",
```suggestion
                "logzioListener": "https://<<LISTENER-HOST>>:8071",
```

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +                "logzioLogLevel": "logzioLogLevel"
```suggestion
                "logzioLogLevel": "<<LOGZIO-LOG-LEVEL>>"
```

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| `logzioOperationsToken` | Your Logz.io [operations token](https://app.logz.io/#/dashboard/settings/general). |
```suggestion
| `<<LOG-SHIPPING-TOKEN>>` | Your Logz.io [operations token](https://app.logz.io/#/dashboard/settings/general). |
```

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| `logzioLogLevel` | Log level for the Lambda function. Defaults to `info`. Valid options are: `debug`, `info`, `warn`, `error`, `fatal`, `panic`. |
```suggestion
| `<<LOGZIO-LOG-LEVEL>>` | Log level for the Lambda function. Defaults to `info`. Valid options are: `debug`, `info`, `warn`, `error`, `fatal`, `panic`. |
```

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +| `logzioListener` | Your Logz.io [listener url](https://docs.logz.io/user-guide/accounts/account-region.html), followed by port `8070` or `8071`. For example, `https://listener.logz.io:8071` |
```suggestion
| `<<LISTENER-HOST>>` | Your Logz.io [listener url](https://docs.logz.io/user-guide/accounts/account-region.html), followed by port `8070` or `8071`. For example, `https://listener.logz.io:8071` |
```

2022-01-30 12:51 UTC, mirii1994 commented on _source/logzio_collections/_security-sources/aws-security-hub.md
> +                "logzioLogLevel": "logzioLogLevel"
```suggestion
                "logzioLogLevel": "<<LOGZIO-LOG-LEVEL>>"
```

2022-01-30 13:35 UTC, ShiranAvidov requested changes
Looks good :) I added couple of comments to aws-cost-and-usage page.

2022-01-30 13:35 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/aws-cost-and-usage-report.md
> +* [Manual configuration](#manual-configuration)
The name of this tab should be "Automated CloudFormation deployment" or something like that (it's not a configuration)

2022-01-30 13:35 UTC, ShiranAvidov commented on _source/logzio_collections/_log-sources/aws-cost-and-usage-report.md
>  AWS Cost and Usage Reports function tracks your AWS usage and provides estimated charges associated with your account. This integration allows you to ship logs from your AWS Cost and Usage Reports to
I think this description and the info box should be in a separate "Overview" tab.

2022-01-30 18:11 UTC, mirii1994 approved these changes
AWS Security Hub is good to go :)

2022-01-31 21:49 UTC, merged