Serverless static logger examples
logzio/logz-docs pull request #2476
Opened 2023-10-19 17:21 UTC by ralongit

Code examples showing best practice to use serverless functions with static clients.

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2023-10-22 06:43 UTC, mirii1994 requested changes

2023-10-22 06:43 UTC, mirii1994 commented on _source/logzio_collections/_log-sources/dotnet.md
> +If you’re using a serverless function, you’ll need to call the appender's flush methods at the end of the function run to make sure the logs are sent before the function finishes its execution. You’l
Since the script is relevant specifically for Azure function, please have it in a separate sub-section of Serverless platforms :)

2023-10-23 06:53 UTC, mirii1994 approved these changes

2023-10-23 09:39 UTC, nico-shishkin approved these changes

2023-10-23 09:41 UTC, merged