Clarify K8s deploy events listener & remove duplicates
logzio/logz-docs pull request #2486
Opened 2023-10-24 12:21 UTC by ralongit

- Remove duplicated token & listener sections.
-  Remove customListener from the standard code sample.
- Clarify the custom listener section

# What changed

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2023-10-24 12:28 UTC, mirii1994 requested changes

2023-10-24 12:28 UTC, mirii1994 commented on _source/logzio_collections/_log-sources/k8s-deploy-events.md
> +Replace `<<CUSTOM-HOST>>` with your listener endpoint URL.
```suggestion
Replace `<<CUSTOM-HOST>>` with your custom endpoint URL. 
```

2023-10-24 12:28 UTC, mirii1994 commented on _source/logzio_collections/_log-sources/k8s-deploy-events.md
> +If you have an HTTP/s endpoint that receives JSON input then by setting the `customListener` secret you can override the Logz.io listener output and route the data to the custom listener instead.
```suggestion
If you have a custom Logz.io listener, you can use the parameter `customListener` and override the Logz.io listener parameter and route the data to the custom listener. 
```

2023-10-25 07:00 UTC, mirii1994 approved these changes

2023-10-25 09:59 UTC, nico-shishkin approved these changes

2023-10-25 09:59 UTC, merged