IN-124-Daemonset-for-filebeat
logzio/logz-docs pull request #720
Opened 2020-10-28 11:29 UTC by fadi-khatib

…tion)

# What changed
Create a DaemonSet for file beat that can applied to the Kubernetes environment:
support 2 configuration options:
1) standard configuration.
2) autodiscovery
  

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2020-11-02 15:06 UTC, mirii1994 requested changes
Great!
A few notes -
* When i'm looking at the netlify preview of this build, there are 2 k8s logos, we need to change it to something else. Here's a screen shot:
https://user-images.githubusercontent.com/37478344/97880664-1bf7f900-1d2a-11eb-8279-271cc7d8324c.png
* See my other comments :)

2020-11-02 15:06 UTC, mirii1994 commented on _source/logzio_collections/_log-sources/filebeat-kubernetes.md
> +
Maybe it's worth to add the download command, something like this - 
```shell
wget link-from-github.com
```
Also, maybe it's worth displaying an example of how a configuration may look? or more extensive note about the _structure_ of the configuration file.
Plus - you accidentally wrote your local path :)

2020-11-02 15:06 UTC, mirii1994 commented on shipping-config-samples/k8s-filebeat.yaml
> +          value: "true"
We'll need to change that. It came to my attention that fields_under_root should always be true, so we need to delete this from the environment variables and to set that field in the configuration to always be true,

```suggestion
```

2020-11-02 15:06 UTC, mirii1994 commented on shipping-config-samples/filebeat-standard-configuration.yaml
> +    fields_under_root: ${FIELDS_UNDER_ROOT}
```suggestion
    fields_under_root: true
```
Please test that it's working when we're changing it to this :)

2020-11-10 19:21 UTC, mirii1994 commented
@fadi-khatib please go over the docs with @shalper , they need some formatting before i'll go over them one last time :)

2020-11-18 19:46 UTC, fadi-khatib reviewed
@shalper @mirii1994, one last change.
we don't want to restrict our customers, I have removed the constraints on 'fields'.and added a note regarding the token.

2020-11-18 19:50 UTC, fadi-khatib reviewed
@shalper @mirii1994, one last change.
we don't want to restrict our customers, I have removed the constraints on 'fields'.and added a note regarding the token.

2020-11-18 19:50 UTC, fadi-khatib commented on _source/logzio_collections/_log-sources/filebeat-kubernetes.md
> -Apply your custom configuration to the paramaters under `filebeat.yml` and only there. The filebeat.yml field contains a basic Filebeat configuration. You should not change the 'fields' and 'output'
@shalper @mirii1994, one last change.
we don't want to restrict our customers, I have removed the constraints on 'fields'.and added a note regarding the token.

2020-11-18 20:14 UTC, mirii1994 approved these changes
Great work! 👏👏👏

2020-11-22 13:28 UTC, merged