update to match 0.0.2
logzio/logz-docs pull request #814
Opened 2020-12-20 10:00 UTC by mirii1994

# What changed

Updated deployment link to use the new multi-threaded version.
Updated the parameters table to match new version.

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

2020-12-20 12:00 UTC, yotamloe approved these changes

2020-12-20 12:52 UTC, Doron-Bargo requested changes
Looking good
Can you update the picture of the URL to represent multi URL?
It should be URLs and not URL

2020-12-21 08:01 UTC, mirii1994 commented
> Looking good
> Can you update the picture of the URL to represent multi URL?
> It should be URLs and not URL

Done, take a look

2020-12-28 08:23 UTC, Doron-Bargo approved these changes
Looking good

2020-12-28 08:26 UTC, merged